[toolchain]
package_manager = "pnpm"
anchor_version = "1.0.2"
solana_version = "3.1.14"

[features]
resolution = true
skip-lint = false

[programs.devnet]
async_vault = "vaLtx8Su1t5P1CZG5GFEMc94sN4K7A4AUUiciadtvUi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
