[toolchain]
solana_version = "2.2.20"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
async_vault = "7M6pdteAnZmj9SEyzjsqUEqfcc4jqhpgLFF9dULDq1iP"

[programs.devnet]
async_vault = "7M6pdteAnZmj9SEyzjsqUEqfcc4jqhpgLFF9dULDq1iP"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
